# [START gae_python37_cloudsql_config]
runtime: python37

env_variables:
  CLOUD_SQL_USERNAME: 'dev'
  CLOUD_SQL_PASSWORD: 'PO9dCbn3DMzkrC90'
  CLOUD_SQL_HOST_NAME: '35.232.245.43'
  CLOUD_SQL_DATABASE_NAME: 'countriesdb'
# [END gae_python37_cloudsql_config]
